name: Primeira-pipeline
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: "minha primiera ação"
        run: echo "Hello pipeline"
      - name: "minha segunda ação"
        run: |
          echo "nossa primeira pipeline"
          echo "FIM"
